name: Build pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Building website to asset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build website
        run: nix develop .# && npm install && npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          # Artifact name
          name: github-page
          # A file, directory or wildcard pattern that describes what to upload
          path: ./dist

  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    needs:
      - build
      # TODO: fix all current build errors
      # - lighthouse-local
    permissions:
      contents: read
      deployments: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: github-page
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
